In [3]:
import stanza

In [4]:
stanza.download('en')

2021-06-04 17:11:36 INFO: Downloading default packages for language: en (English)...
2021-06-04 17:11:37 INFO: File exists: C:\Users\Chuancey\stanza_resources\en\default.zip.
2021-06-04 17:11:40 INFO: Finished downloading models and saved to C:\Users\Chuancey\stanza_resources.


In [7]:
nlp = stanza.Pipeline(lang='en', processors='tokenize, mwt, pos, lemma, depparse', tokenize_no_ssplit=True)

2021-06-04 17:12:16 WARNING: Can not find mwt: default from official model list. Ignoring it.
2021-06-04 17:12:16 INFO: Loading these models for language: en (English):
| Processor | Package  |
------------------------
| tokenize  | combined |
| pos       | combined |
| lemma     | combined |
| depparse  | combined |

2021-06-04 17:12:16 INFO: Use device: cpu
2021-06-04 17:12:16 INFO: Loading: tokenize
2021-06-04 17:12:16 INFO: Loading: pos
2021-06-04 17:12:16 INFO: Loading: lemma
2021-06-04 17:12:17 INFO: Loading: depparse
2021-06-04 17:12:17 INFO: Done loading processors!


In [8]:
t = "dome petroleum 's reaffirms dome mines stake for sale at right price spokesman 'says'"

In [9]:
doc = nlp(t)

In [10]:
print(*[f'id: {word.id}\tword: {word.text}\thead id: {word.head}\thead: {sent.words[word.head-1].text if word.head > 0 else "root"}\tdeprel: {word.deprel}' for sent in doc.sentences for word in sent.words], sep='\n')

id: 1	word: dome	head id: 2	head: petroleum	deprel: compound
id: 2	word: petroleum	head id: 4	head: reaffirms	deprel: nmod:poss
id: 3	word: 's	head id: 2	head: petroleum	deprel: case
id: 4	word: reaffirms	head id: 7	head: stake	deprel: compound
id: 5	word: dome	head id: 7	head: stake	deprel: compound
id: 6	word: mines	head id: 7	head: stake	deprel: compound
id: 7	word: stake	head id: 15	head: says	deprel: ccomp
id: 8	word: for	head id: 9	head: sale	deprel: case
id: 9	word: sale	head id: 7	head: stake	deprel: nmod
id: 10	word: at	head id: 13	head: spokesman	deprel: case
id: 11	word: right	head id: 13	head: spokesman	deprel: amod
id: 12	word: price	head id: 13	head: spokesman	deprel: compound
id: 13	word: spokesman	head id: 9	head: sale	deprel: nmod
id: 14	word: '	head id: 13	head: spokesman	deprel: punct
id: 15	word: says	head id: 0	head: root	deprel: root
id: 16	word: '	head id: 15	head: says	deprel: punct


In [12]:
print(*[f'id: {word.id}\tword: {word.text}\thead id: {word.head}\thead: {sent.words[word.head-1].text if word.head > 0 else "root"}\tdeprel: {word.deprel}' for sent in doc.sentences for word in sent.words], sep='\n')

id: 1	word: replication	head id: 2	head: patterns	deprel: compound
id: 2	word: patterns	head id: 26	head: studied	deprel: nsubj:pass
id: 3	word: of	head id: 6	head: x	deprel: case
id: 4	word: the	head id: 6	head: x	deprel: det
id: 5	word: fragile	head id: 6	head: x	deprel: amod
id: 6	word: x	head id: 2	head: patterns	deprel: nmod
id: 7	word: in	head id: 10	head: analysis	deprel: case
id: 8	word: heterozygous	head id: 9	head: carriers	deprel: amod
id: 9	word: carriers	head id: 10	head: analysis	deprel: compound
id: 10	word: analysis	head id: 6	head: x	deprel: nmod
id: 11	word: by	head id: 15	head: method	deprel: case
id: 12	word: a	head id: 15	head: method	deprel: det
id: 13	word: brdurd	head id: 15	head: method	deprel: amod
id: 14	word: antibody	head id: 15	head: method	deprel: compound
id: 15	word: method	head id: 10	head: analysis	deprel: nmod
id: 16	word: .	head id: 2	head: patterns	deprel: punct
id: 17	word: the	head id: 19	head: status	deprel: det
id: 18	word: replication	head id:

In [ ]:
anti_rel = ['punct','cop','case','det','root','cc','mark','aux','advmod','fixed','nummod','aux:pass']

In [5]:
doc = nlp("Superficial cultures in neonatal sepsis evaluations. Impact on antibiotic decision making. The authors performed a retrospective analysis of neonatal superficial cultures and their effect on antimicrobial decision making during a nine-month period at Nashville General Hospital. They obtained and reviewed charts of infants (n = 66) having paired superficial (skin and/or gastric aspirate) and deep (blood and cerebrospinal fluid) cultures for the evaluation of early-onset sepsis. Superficial cultures were positive for pathogens (any streptococcus or enteric gram-negative) in 15% (10/66) of cases. Antimicrobial decision making was affected in only one of these cases, and in a seemingly inappropriate manner. In summary, there was no evidence or review that superficial cultures used in sepsis evaluation influenced physician antimicrobial decision making; in one case they may have led to unnecessary antibiotic exposure.")

In [17]:
doc = nlp('in perrys good and his is an interesting character , but " serving sara " hasn\'t much more to serve than silly fluff . nor is it a romantic comedy .')

In [18]:
print(*[f'id: {word.id}\tword: {word.text}\thead id: {word.head}\thead: {sent.words[word.head-1].text if word.head > 0 else "root"}\tdeprel: {word.deprel}' for sent in doc.sentences for word in sent.words], sep='\n')

id: 1	word: in	head id: 2	head: u	deprel: case
id: 2	word: u	head id: 6	head: good	deprel: obl
id: 3	word: .	head id: 6	head: good	deprel: punct
id: 4	word: s	head id: 6	head: good	deprel: cop
id: 5	word: perrys	head id: 6	head: good	deprel: nsubj
id: 6	word: good	head id: 0	head: root	deprel: root
id: 7	word: and	head id: 12	head: character	deprel: cc
id: 8	word: his	head id: 12	head: character	deprel: nsubj
id: 9	word: is	head id: 12	head: character	deprel: cop
id: 10	word: an	head id: 12	head: character	deprel: det
id: 11	word: interesting	head id: 12	head: character	deprel: amod
id: 12	word: character	head id: 6	head: good	deprel: conj
id: 13	word: ,	head id: 22	head: more	deprel: punct
id: 14	word: but	head id: 22	head: more	deprel: cc
id: 15	word: "	head id: 16	head: serving	deprel: punct
id: 16	word: serving	head id: 22	head: more	deprel: csubj
id: 17	word: sara	head id: 16	head: serving	deprel: obj
id: 18	word: "	head id: 16	head: serving	deprel: punct
id: 19	word: has	head id:

In [5]:
doc.sentences[1].print_dependencies()

('Impact', 0, 'root')
('on', 5, 'case')
('antibiotic', 4, 'amod')
('decision', 5, 'compound')
('making', 1, 'nmod')
('.', 1, 'punct')


In [1]:
import nltk
from nltk.corpus import stopwords
from collections import Counter
import re
import joblib
import numpy as np
from tqdm import tqdm
import itertools
import scipy.sparse as sp

In [2]:
# 数据集
dataset = "ohsumed"

In [3]:
# param
stop_words = set(stopwords.words('english'))
least_freq = 5
if dataset == "mr" or "SST" in dataset:
    stop_words = set()
    least_freq = 0

In [4]:
split = joblib.load(f"nlp_temp/{dataset}.split.pkl")
edge = joblib.load(f"nlp_temp/{dataset}.edge.pkl")
pos= joblib.load(f"nlp_temp/{dataset}.pos.pkl")

In [5]:
word2count = Counter([w for t in split for w in t])
word_count = [[w, c] for w, c in word2count.items() if c >= least_freq and w not in stop_words]
word2index = {w: i for i, (w, c) in enumerate(word_count)}

In [6]:
len(split[0])

153

In [7]:
len(edge[0])

153

In [8]:
edge[0][-10:]

[(144, 141),
 (145, 148),
 (146, 148),
 (147, 148),
 (148, 137),
 (149, 152),
 (150, 152),
 (151, 152),
 (152, 148),
 (153, 2)]

In [16]:
def words_split_pos_edge(split, pos, edge, word2index):
    split_list = []
    pos_list = []
    edge_list = []
    for t, p, ed in tqdm(zip(split, pos, edge)):
        temp = []
        temp_pos = []
        k = -1
        for i in range(0, len(t)):
            if t[i] in word2index:
                temp.append(t[i])
                temp_pos.append(p[i])
            else:
                temp_edge = []
                k += 1
                for e in ed:
                    e = list(e)
                    if e[0] == i+1-k or e[1] == i+1-k:
                        continue
                    if e[0] > i+1-k:
                        e[0] = e[0] - 1
                    if e[1] > i+1-k:
                        e[1] = e[1] - 1
                    temp_edge.append(tuple(e))
                ed = temp_edge
        split_list.append(temp)
        pos_list.append(temp_pos)
        edge_list.append(ed)
    return split_list, pos_list, edge_list

In [17]:
s, p, e = words_split_pos_edge(split, pos, edge, word2index)

7400it [01:16, 97.12it/s] 


In [28]:
e[0]

[(1, 2),
 (2, 0),
 (3, 5),
 (4, 5),
 (5, 2),
 (6, 2),
 (7, 2),
 (8, 9),
 (9, 7),
 (10, 7),
 (11, 13),
 (12, 13),
 (13, 2),
 (14, 15),
 (15, 13),
 (16, 18),
 (17, 18),
 (18, 15),
 (19, 15),
 (20, 21),
 (21, 19),
 (22, 19),
 (23, 24),
 (24, 25),
 (25, 22),
 (26, 27),
 (27, 25),
 (28, 2),
 (29, 13),
 (30, 29),
 (31, 29),
 (32, 31),
 (33, 34),
 (34, 32),
 (35, 34),
 (36, 34),
 (37, 31),
 (38, 37),
 (39, 40),
 (40, 38),
 (41, 42),
 (42, 40),
 (43, 42),
 (44, 50),
 (45, 46),
 (46, 50),
 (47, 48),
 (48, 46),
 (49, 48),
 (50, 58),
 (51, 50),
 (52, 54),
 (53, 54),
 (54, 51),
 (55, 58),
 (56, 57),
 (57, 58),
 (58, 13),
 (59, 58),
 (60, 61),
 (61, 59),
 (62, 63),
 (63, 64),
 (64, 61),
 (65, 61),
 (66, 61),
 (67, 69),
 (68, 69),
 (69, 66),
 (70, 69),
 (71, 66),
 (72, 76),
 (73, 74),
 (74, 75),
 (75, 76),
 (76, 59),
 (77, 76),
 (78, 77),
 (79, 82),
 (80, 81),
 (81, 82),
 (82, 77),
 (84, 82),
 (87, 86),
 (88, 89),
 (89, 93),
 (90, 89),
 (91, 92),
 (92, 90),
 (94, 96),
 (95, 96),
 (96, 93),
 (97, 93)

In [8]:
from stanfordcorenlp import StanfordCoreNLP

In [9]:
nlp = StanfordCoreNLP('.\stanford-corenlp-4.2.0')

In [13]:
text = "'moore is like a progressive bull in a china shop , a provocateur crashing into ideas and special interest groups as he slaps together his own brand of liberalism '"

In [15]:
nlp.dependency_parse(text)

[('ROOT', 0, 6),
 ('nsubj', 6, 1),
 ('cop', 6, 2),
 ('case', 6, 3),
 ('det', 6, 4),
 ('amod', 6, 5),
 ('case', 10, 7),
 ('det', 10, 8),
 ('compound', 10, 9),
 ('nmod', 6, 10),
 ('punct', 10, 11),
 ('det', 13, 12),
 ('nsubj', 14, 13),
 ('dep', 10, 14),
 ('case', 16, 15),
 ('obl', 14, 16),
 ('cc', 20, 17),
 ('amod', 20, 18),
 ('compound', 20, 19),
 ('conj', 16, 20),
 ('mark', 23, 21),
 ('nsubj', 23, 22),
 ('advcl', 14, 23),
 ('advmod', 23, 24),
 ('nmod:poss', 27, 25),
 ('amod', 27, 26),
 ('obj', 23, 27),
 ('case', 29, 28),
 ('nmod', 27, 29)]

In [5]:
from nltk.corpus import stopwords

In [6]:
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [148]:
import torch

In [149]:
a = torch.tensor([[1,2,3,4,5],[1,2,3,4,5]])

In [152]:
torch.stack((a, a, a), dim=1).shape

torch.Size([2, 3, 5])

In [151]:
a.shape

torch.Size([2, 5])

In [146]:
a.unsqueeze(0)

tensor([[[1, 2, 3, 4, 5],
         [1, 2, 3, 4, 5]]])

In [147]:
a.shape

torch.Size([2, 5])

In [128]:
b = torch.nn.Parameter(torch.Tensor([1]), requires_grad=True)

In [129]:
b

Parameter containing:
tensor([1.], requires_grad=True)

In [130]:
(1 - b) * a

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], grad_fn=<MulBackward0>)

In [131]:
b

Parameter containing:
tensor([1.], requires_grad=True)

In [132]:
a*b

tensor([[1., 2., 3., 4., 5.],
        [1., 2., 3., 4., 5.]], grad_fn=<MulBackward0>)